name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main   # větev, ze které se spouští build

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repozitáře s podporou submodulů
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true   # aby se stáhl submodul Ananke

    # 2️⃣ Setup Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.115.0'   # nebo nejnovější dostupná verze

    # 3️⃣ Build stránky
    - name: Build
      run: hugo --minify

    # 4️⃣ Deploy na GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        # volitelné nastavení:
        # user_name: "github-actions"
        # user_email: "github-actions@github.com"
        # force_orphan: true
